# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  BUILD_ID: $(Build.BuildId)
  VERSION: '1.0'
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'complete/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    mavenAuthenticateFeed: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'deploy'
